/**
 * Retos genéricos de la fase 1. Ya no forman parte de la biblioteca: solo se
 * usan al migrar datos antiguos para conservar el historial de retos completados.
 */
type LegacyChallenge = { id: string; title: string; description: string; type: import('../../models/types').ChallengeType; reward: { points: number }; emoji: string; [k: string]: unknown };

export const LEGACY_CHALLENGES: LegacyChallenge[] = [
  {
    id: 'ch-love-note',
    title: 'Notita escondida',
    description: 'Escondan una nota con algo que aman del otro donde la encuentre mañana.',
    type: 'romantic',
    reward: { points: 80 },
    difficulty: 'easy',
    tags: ['detalle', 'escrito'],
    pack: 'base',
    emoji: '💌',
  },
  {
    id: 'ch-no-phones',
    title: 'Noche sin celulares',
    description: 'Desde la cena hasta dormir: teléfonos en otro cuarto.',
    type: 'experience',
    reward: { points: 120 },
    difficulty: 'medium',
    tags: ['conexión'],
    pack: 'base',
    emoji: '📵',
  },
  {
    id: 'ch-slow-dance',
    title: 'Baile lento',
    description: 'Pongan una canción que les guste y bailen en la sala, sin prisa.',
    type: 'romantic',
    reward: { points: 60 },
    difficulty: 'easy',
    tags: ['música'],
    pack: 'base',
    emoji: '💃',
  },
  {
    id: 'ch-double-points',
    title: 'Día de puntos dobles',
    description: 'Registren ❤️ hoy y reclamen este bonus extra.',
    type: 'bonus',
    reward: { points: 100 },
    difficulty: 'easy',
    tags: ['bonus'],
    pack: 'base',
    emoji: '✨',
  },
  {
    id: 'ch-massage',
    title: 'Masaje de 10 minutos',
    description: 'Turnos de 10 minutos cada uno. Con aceite o crema si tienen.',
    type: 'romantic',
    reward: { points: 100 },
    difficulty: 'easy',
    tags: ['relajación'],
    pack: 'base',
    emoji: '🫶',
  },
  {
    id: 'ch-36-questions',
    title: '5 preguntas profundas',
    description: 'Háganse 5 preguntas que nunca se hayan hecho. Nada de respuestas cortas.',
    type: 'experience',
    reward: { points: 90 },
    difficulty: 'medium',
    tags: ['conversación'],
    pack: 'base',
    emoji: '🧠',
  },
  {
    id: 'ch-surprise-snack',
    title: 'Antojo sorpresa',
    description: 'Uno de los dos trae un antojo sorpresa. El otro adivina qué es antes de verlo.',
    type: 'surprise',
    reward: { points: 70 },
    difficulty: 'easy',
    tags: ['comida', 'sorpresa'],
    pack: 'base',
    emoji: '🍫',
  },
  {
    id: 'ch-new-place',
    title: 'Un lugar nuevo',
    description: 'Vayan juntos a un lugar donde nunca hayan estado, aunque sea una tienda.',
    type: 'experience',
    reward: { points: 150 },
    difficulty: 'hard',
    tags: ['salir'],
    pack: 'base',
    emoji: '🗺️',
  },
  {
    id: 'ch-compliments',
    title: 'Lluvia de cumplidos',
    description: 'Cada uno dice 5 cosas que admira del otro, mirándose a los ojos.',
    type: 'romantic',
    reward: { points: 80 },
    difficulty: 'easy',
    tags: ['palabras'],
    pack: 'base',
    emoji: '🌷',
  },
  {
    id: 'ch-mystery',
    title: 'Plan misterioso',
    description: 'Uno organiza algo de 30 minutos sin decir qué es. El otro solo se deja llevar.',
    type: 'surprise',
    reward: { points: 130 },
    difficulty: 'medium',
    tags: ['sorpresa'],
    pack: 'base',
    emoji: '🎁',
  },
  {
    id: 'ch-valentine',
    title: 'San Valentín',
    description: 'Hoy es su día: cada uno prepara un detalle hecho a mano.',
    type: 'special',
    reward: { points: 300 },
    difficulty: 'medium',
    tags: ['fecha especial'],
    fixedDate: '02-14',
    pack: 'base',
    emoji: '💘',
  },
];
