import type { DateIdea } from '../models/types';

/**
 * Biblioteca de citas (ejemplos de la Fase 1).
 * Cada cita es una EXPERIENCIA con dinámica, no solo una actividad.
 * Para agregar más, añade objetos a este arreglo (o crea más archivos y
 * concaténalos en DATE_LIBRARY). Ningún componente depende del contenido.
 */
export const DATE_IDEAS: DateIdea[] = [
  {
    id: 'sunset-date',
    title: 'Sunset Date',
    emoji: '🌅',
    description: 'Persigan el atardecer. Cada uno lleva una pregunta secreta para cuando el sol toque el horizonte.',
    category: 'romantic',
    tags: ['atardecer', 'preguntas'],
    budget: 'free',
    duration: 'hours',
    location: ['outdoors'],
    energy: 'low',
    mood: ['romantic', 'calm', 'conversation'],
    spontaneity: 2,
    difficulty: 1,
    preparation: ['Revisen a qué hora se pone el sol', 'Una manta o chamarra'],
    instructions: [
      'Elijan un lugar alto o con vista al mar.',
      'Lleguen 30 minutos antes y caminen sin celular.',
      'Justo cuando el sol toque el horizonte, cada uno hace su pregunta secreta.',
    ],
    optionalTwist: 'Tomen una sola foto cada uno. Sin repetir. Compárenlas al final.',
    dynamics: ['questions', 'rules'],
    ingredients: ['outdoors'],
    points: 150,
  },
  {
    id: 'blind-restaurant',
    title: 'Restaurante a ciegas',
    emoji: '🎲',
    description: 'Cada uno elige un restaurante sin decírselo al otro. El azar decide a cuál van.',
    category: 'food',
    tags: ['restaurante', 'azar'],
    budget: 'moderate',
    duration: 'hours',
    location: ['restaurant', 'city'],
    energy: 'medium',
    mood: ['fun', 'random'],
    spontaneity: 2,
    difficulty: 1,
    preparation: ['Dos papelitos'],
    instructions: [
      'Cada uno escribe un restaurante en un papel sin enseñarlo.',
      'Doblen los papeles y revuélvanlos.',
      'Uno saca el papel ganador: ahí van, sin quejas.',
      'Quien perdió elige el postre.',
    ],
    optionalTwist: 'Cada uno pide el platillo del otro.',
    dynamics: ['random-decision', 'rules'],
    ingredients: ['restaurant'],
    points: 150,
  },
  {
    id: 'movie-roulette',
    title: 'Ruleta de películas',
    emoji: '🍿',
    description: 'Tres películas, tres pistas, una elección a ciegas. Con snacks temáticos.',
    category: 'movie',
    tags: ['película', 'casa', 'snacks'],
    budget: 'low',
    duration: 'night',
    location: ['home'],
    energy: 'low',
    mood: ['calm', 'fun'],
    spontaneity: 1,
    difficulty: 1,
    preparation: ['Palomitas o snacks', 'Una cobija grande'],
    instructions: [
      'Cada uno propone 3 películas, pero solo describe cada una con 3 palabras.',
      'El otro elige una solo por las pistas.',
      'Preparen un snack que combine con la película.',
    ],
    optionalTwist: 'Si alguien se duerme antes del final, elige la próxima el otro.',
    dynamics: ['game', 'random-decision'],
    ingredients: ['home'],
    points: 100,
  },
  {
    id: 'cinema-surprise',
    title: 'Cine sorpresa',
    emoji: '🎬',
    description: 'Vayan al cine y elijan la película que empiece más pronto, sin leer de qué trata.',
    category: 'movie',
    tags: ['cine', 'espontáneo'],
    budget: 'moderate',
    duration: 'hours',
    location: ['cinema'],
    energy: 'medium',
    mood: ['random', 'fun'],
    spontaneity: 3,
    difficulty: 1,
    preparation: [],
    instructions: [
      'Lleguen al cine sin haber revisado la cartelera.',
      'Compren boletos para la próxima función disponible.',
      'Prohibido ver el tráiler o la sinopsis.',
      'Al salir, califiquen la película del 1 al 10 al mismo tiempo.',
    ],
    optionalTwist: 'Quien le dé la calificación más baja paga los helados.',
    dynamics: ['random-decision', 'surprise', 'competition'],
    ingredients: ['cinema', 'unexpected'],
    points: 150,
  },
  {
    id: 'paint-each-other',
    title: 'Retrato a ciegas',
    emoji: '🎨',
    description: 'Dibújense sin mirar la hoja. El resultado va directo al refri.',
    category: 'creative',
    tags: ['arte', 'risas'],
    budget: 'free',
    duration: 'quick',
    location: ['home', 'anywhere'],
    energy: 'low',
    mood: ['creative', 'fun'],
    spontaneity: 3,
    difficulty: 1,
    preparation: ['Hojas y plumas o colores'],
    instructions: [
      'Siéntense frente a frente.',
      'Dibujen al otro durante 2 minutos SIN mirar la hoja.',
      'Hagan 3 rondas cambiando de mano.',
      'Elijan el mejor y fírmenlo con fecha.',
    ],
    optionalTwist: 'Última ronda: dibújense como se imaginan a los 80 años.',
    dynamics: ['game', 'creativity'],
    ingredients: ['home', 'creative'],
    points: 80,
  },
  {
    id: 'picnic-alphabet',
    title: 'Picnic del alfabeto',
    emoji: '🧺',
    description: 'Una letra al azar decide todo lo que va en la canasta.',
    category: 'outdoors',
    tags: ['picnic', 'parque'],
    budget: 'low',
    duration: 'hours',
    location: ['outdoors'],
    energy: 'medium',
    mood: ['fun', 'romantic', 'creative'],
    spontaneity: 2,
    difficulty: 2,
    preparation: ['Canasta o mochila', 'Manta'],
    instructions: [
      'Elijan una letra al azar.',
      'Cada uno compra 3 cosas que empiecen con esa letra, sin enseñarlas.',
      'Ábranlas en el parque como si fuera un intercambio.',
    ],
    optionalTwist: 'Agreguen una canción que empiece con la letra para escucharla ahí.',
    dynamics: ['random-decision', 'surprise', 'rules'],
    ingredients: ['picnic', 'outdoors'],
    points: 150,
  },
  {
    id: 'coffee-questions',
    title: 'Café y 3 preguntas',
    emoji: '☕',
    description: 'Un café nuevo y tres preguntas que suben de intensidad.',
    category: 'cheap',
    tags: ['café', 'conversación'],
    budget: 'low',
    duration: 'quick',
    location: ['city'],
    energy: 'low',
    mood: ['conversation', 'calm'],
    spontaneity: 2,
    difficulty: 1,
    preparation: [],
    instructions: [
      'Busquen un café donde nunca hayan ido.',
      'Pregunta 1: ¿qué te hizo sonreír esta semana?',
      'Pregunta 2: ¿qué te gustaría que hiciéramos más seguido?',
      'Pregunta 3: ¿qué sueño no le has contado a nadie?',
    ],
    optionalTwist: 'Pidan la bebida que el otro elija para ustedes.',
    dynamics: ['questions'],
    ingredients: ['cafe'],
    points: 80,
  },
  {
    id: 'cook-off',
    title: 'Duelo de chefs',
    emoji: '👩‍🍳',
    description: 'Mismo presupuesto, mismos ingredientes base, dos platillos. Jueces: ustedes mismos.',
    category: 'food',
    tags: ['cocina', 'competencia', 'casa'],
    budget: 'low',
    duration: 'hours',
    location: ['home'],
    energy: 'high',
    mood: ['competitive', 'fun', 'creative'],
    spontaneity: 1,
    difficulty: 2,
    preparation: ['$150 por persona para ingredientes'],
    instructions: [
      'Vayan juntos al súper, pero compren por separado.',
      'Cada uno tiene 40 minutos para cocinar.',
      'Presenten el plato con nombre elegante.',
      'Califiquen sabor, presentación y creatividad.',
    ],
    optionalTwist: 'Ingrediente sorpresa obligatorio elegido por el otro.',
    dynamics: ['competition', 'challenge', 'creativity'],
    ingredients: ['home', 'creative'],
    points: 180,
  },
  {
    id: 'road-trip-coin',
    title: 'Road trip de la moneda',
    emoji: '🪙',
    description: 'En cada cruce, una moneda decide: águila derecha, sol izquierda.',
    category: 'adventure',
    tags: ['carro', 'azar', 'explorar'],
    budget: 'low',
    duration: 'hours',
    location: ['car'],
    energy: 'high',
    mood: ['adventurous', 'random', 'fun'],
    spontaneity: 3,
    difficulty: 2,
    preparation: ['Tanque lleno', 'Una moneda', 'Playlist'],
    instructions: [
      'Salgan sin destino.',
      'En cada cruce importante, lancen la moneda.',
      'Después de 45 minutos, paren en el primer lugar interesante.',
      'Regresen por otro camino.',
    ],
    optionalTwist: 'Solo pueden comer en un lugar que nunca hayan visto antes.',
    dynamics: ['random-decision', 'rules', 'surprise'],
    ingredients: ['roadtrip', 'unexpected'],
    points: 200,
  },
  {
    id: 'stargazing',
    title: 'Noche de estrellas',
    emoji: '🌌',
    description: 'Lejos de las luces, inventen sus propias constelaciones.',
    category: 'romantic',
    tags: ['estrellas', 'noche'],
    budget: 'free',
    duration: 'night',
    location: ['outdoors', 'car'],
    energy: 'low',
    mood: ['romantic', 'calm', 'conversation'],
    spontaneity: 2,
    difficulty: 2,
    preparation: ['Manta', 'Algo calientito para tomar'],
    instructions: [
      'Manejen a un lugar oscuro y seguro.',
      'Cada uno inventa una constelación y su historia.',
      'Pónganle a una estrella el nombre de algo que vivieron juntos.',
    ],
    optionalTwist: 'Escriban un deseo cada uno y ábranlos en un año.',
    dynamics: ['creativity', 'questions'],
    ingredients: ['outdoors', 'roadtrip'],
    points: 150,
  },
  {
    id: 'thrift-challenge',
    title: 'Outfit de $100',
    emoji: '🛍️',
    description: 'Vístanse el uno al otro en una tienda de segunda mano con $100.',
    category: 'fun',
    tags: ['compras', 'risas', 'reto'],
    budget: 'low',
    duration: 'hours',
    location: ['city'],
    energy: 'high',
    mood: ['fun', 'competitive', 'creative'],
    spontaneity: 2,
    difficulty: 2,
    preparation: ['$100 cada uno'],
    instructions: [
      'Cada uno tiene 20 minutos y $100 para armar un outfit para el otro.',
      'No se vale ver lo que el otro elige.',
      'Revelación en el probador.',
      'Usen el outfit el resto de la cita.',
    ],
    optionalTwist: 'Tema secreto: cada uno elige un tema y el otro lo tiene que adivinar.',
    dynamics: ['challenge', 'competition', 'surprise'],
    ingredients: ['unexpected', 'creative'],
    points: 180,
  },
  {
    id: 'spa-night',
    title: 'Spa en casa',
    emoji: '🛁',
    description: 'Luces bajas, mascarillas, música suave y un masaje por turnos.',
    category: 'home',
    tags: ['relajación', 'casa'],
    budget: 'low',
    duration: 'hours',
    location: ['home'],
    energy: 'low',
    mood: ['romantic', 'calm'],
    spontaneity: 1,
    difficulty: 1,
    preparation: ['Mascarillas', 'Velas', 'Aceite o crema'],
    instructions: [
      'Preparen el espacio: velas, toallas y playlist tranquila.',
      'Mascarilla juntos (sí, los dos).',
      'Masaje por turnos de 15 minutos.',
    ],
    optionalTwist: 'Cada uno escribe el "menú de servicios" del spa para el otro.',
    dynamics: ['rules', 'creativity'],
    ingredients: ['home'],
    points: 120,
  },
  {
    id: 'tourist-day',
    title: 'Turistas en su ciudad',
    emoji: '📸',
    description: 'Hoy son turistas: fotos cursis, lugares típicos y cero rutina.',
    category: 'adventure',
    tags: ['ciudad', 'fotos'],
    budget: 'moderate',
    duration: 'day',
    location: ['city'],
    energy: 'high',
    mood: ['adventurous', 'fun'],
    spontaneity: 2,
    difficulty: 2,
    preparation: ['Lista de 5 lugares "típicos"'],
    instructions: [
      'Cada uno elige 2 lugares; el quinto lo decide el azar.',
      'Tomen una foto de turista en cada lugar.',
      'Coman algo típico que nunca hayan probado.',
    ],
    optionalTwist: 'Hablen con acento de otro país todo el día.',
    dynamics: ['challenge', 'random-decision'],
    ingredients: ['outdoors', 'unexpected'],
    points: 220,
  },
  {
    id: 'anniversary-recreate',
    title: 'Recrear la primera cita',
    emoji: '✨',
    description: 'Vuelvan al lugar (o a la idea) de su primera cita, con una sorpresa nueva.',
    category: 'special',
    tags: ['aniversario', 'nostalgia'],
    budget: 'special',
    duration: 'night',
    location: ['restaurant', 'city', 'anywhere'],
    energy: 'medium',
    mood: ['romantic', 'conversation'],
    spontaneity: 1,
    difficulty: 3,
    preparation: ['Recuerden qué llevaban puesto', 'Una sorpresa pequeña cada uno'],
    instructions: [
      'Recreen lo más posible la primera cita.',
      'Cuenten qué pensaban el uno del otro ese día.',
      'Intercambien la sorpresa al final.',
    ],
    optionalTwist: 'Escriban una carta al "yo" de esa primera cita.',
    dynamics: ['surprise', 'questions'],
    ingredients: ['restaurant', 'unexpected'],
    points: 300,
  },
  {
    id: 'game-night',
    title: 'Torneo de juegos',
    emoji: '🎮',
    description: 'Tres juegos, un marcador y un premio que el ganador elige.',
    category: 'fun',
    tags: ['juegos', 'casa', 'competencia'],
    budget: 'free',
    duration: 'hours',
    location: ['home'],
    energy: 'medium',
    mood: ['competitive', 'fun'],
    spontaneity: 3,
    difficulty: 1,
    preparation: ['Cartas, juego de mesa o videojuego'],
    instructions: [
      'Elijan 3 juegos distintos.',
      'Antes de empezar, cada uno escribe el premio que quiere si gana.',
      'Al mejor de 3.',
    ],
    optionalTwist: 'El perdedor de cada ronda dice un cumplido obligatorio.',
    dynamics: ['game', 'competition'],
    ingredients: ['home'],
    points: 100,
  },
  {
    id: 'breakfast-in-bed',
    title: 'Desayuno en la cama',
    emoji: '🥞',
    description: 'Uno cocina, el otro no puede salir de la cama. Mañana se invierten los papeles.',
    category: 'home',
    tags: ['desayuno', 'mañana'],
    budget: 'low',
    duration: 'quick',
    location: ['home'],
    energy: 'low',
    mood: ['romantic', 'calm'],
    spontaneity: 2,
    difficulty: 1,
    preparation: ['Ingredientes del desayuno favorito del otro'],
    instructions: [
      'Despiértense antes que el otro.',
      'Preparen su desayuno favorito.',
      'Sírvanlo con una nota.',
    ],
    optionalTwist: 'Menú con nombres inventados de restaurante elegante.',
    dynamics: ['surprise'],
    ingredients: ['home'],
    points: 90,
  },
];

export const DATE_LIBRARY: DateIdea[] = [...DATE_IDEAS];
